### ISSUE TITLE
image is private, can not pull

### ISSUE THREAD

**Issue by LGinC** [cxfksword/douban-api-rs#1]
`ghcr.io/cxfksword/douban-api-rs` image is private default
```bash
Error response from daemon: Head "https://ghcr.io/v2/cxfksword/douban-api-rs/manifests/latest": unauthorized
```

镜像默认设置是private的,需要改为public才能匿名拉取

**Comment by cxfksword** [comment]
项目依赖了actix-web，第一次是比较慢

windows最好用msvc编译，不要用mingw，我打开github action编译windows版😂
