### ISSUE TITLE
用isbn和douban id点查时，publisher和tag信息大概率丢失

### ISSUE THREAD

**Issue by shentar** [cxfksword/douban-api-rs#11]
分析了一下，是因为某些场景，出版社可能是个超链接，按照plain text解析会解析不到东西；tag信息丢失不知道是什么原因。

**Comment by cxfksword** [comment]
数据来源是网页版，tag看了下网页版是没有，publisher应该是bug，要等修复

**Comment by cxfksword** [comment]
最新v0.2.10已修复publisher问题了

**Comment by LGinC** [comment]
@shentar 豆瓣网页现在已经取消tag显示了，所以获取不到
