### ISSUE TITLE
是否考虑部署到 vercel 上作为 api

### ISSUE THREAD

**Issue by lmm214** [cxfksword/douban-api-rs#12]
vercel 支持静态api部署

**Comment by LGinC** [comment]
放到静态网站里访问人一多立马就被豆瓣限制了,所以还得是自己部署一套自己用

**Comment by LGinC** [comment]
得,我这就已经被限制了
![image](https://user-images.githubusercontent.com/15363011/160049490-c26522b4-85be-42e0-ac27-9211bf36113c.png)

**Comment by cxfksword** [comment]
有防爬虫，推荐docker部署自己用
