### ISSUE TITLE
请教一下 这个怎么用啊？能不能简单写下步骤？

### ISSUE THREAD

**Issue by leeyonwang** [cxfksword/douban-api-rs#14]
我把地址写进opendouban设置的地址里 刮削不了啊 
我试了下 http://192.168.2.192:82/movies?q={福冈}  无法访问 （我没有映射到80 端口冲突 到82了）
是我哪一步错了吗？

**Comment by cxfksword** [comment]
接口无法访问的话，应该是你docker部署有问题，你可以看下docker日志或绑定另一个端口试下
