### ISSUE TITLE
不能刮削演员饰演的校色名称。

### ISSUE THREAD

**Issue by fallenyy** [cxfksword/douban-api-rs#15]
演员饰演的角色名称统一显示为“演员”，没有角色名称，豆瓣里是有角色名称的。

**Comment by cxfksword** [comment]
jellyfin-plugin-opendouban插件有限制，改了会不显示演员表，暂时不处理

**Comment by cxfksword** [comment]
v0.3.0已改为返回详细角色名，需要搭配最新版jellyfin-plugin-opendouban插件使用

**Comment by fallenyy** [comment]
> 


太棒了，试了一下，感觉舒服多了，原谅我的强迫症，感谢！
