### ISSUE TITLE
您好，请问下这个在群辉nas中怎么安装呢？

### ISSUE THREAD

**Issue by Huster1993** [cxfksword/douban-api-rs#16]
搜了一下也没有找到相关的教程。
在docker注册表里没有搜到这个项目。

**Comment by libsu** [comment]
> 1. 终端进nas

`ssh admin@10.0.0.190`
`sudo su`
_admin=用户，10.0.0.190= nas地址_

> 2. 安装运行并配置

`docker run -d --name=douban-api-rs --restart=unless-stopped -p **5000**:80 ghcr.io/cxfksword/douban-api-rs:latest`
_5000=端口号，按需修改，配置成功后api地址为：http://10.0.0.190:5000 或http://localhost:5000_

**Comment by cxfksword** [comment]
我没上传到dockerhub，不过镜像加上域名也是能直接pull下来的：`ghcr.io/cxfksword/douban-api-rs`
