### ISSUE TITLE
doucker hub 搜索不到镜像

### ISSUE THREAD

**Issue by gzsxy** [cxfksword/douban-api-rs#9]
使用 cxfksword/douban-api-rs在docker hub 无法搜索到镜像。请问应该使用什么名称搜索？

**Comment by cxfksword** [comment]
我没推到dockerhub，只放在ghcr，拉镜像要带域名
docker pull ghcr.io/cxfksword/douban-api-rs:latest

**Comment by gzsxy** [comment]
> 我没推到dockerhub，只放在ghcr，拉镜像要带域名 docker pull ghcr.io/cxfksword/douban-api-rs:latest

**Comment by gzsxy** [comment]
> 我没推到dockerhub，只放在ghcr，拉镜像要带域名 docker pull ghcr.io/cxfksword/douban-api-rs:latest

好的，稍后我试试。
